### ISSUE TITLE
tarball for 1.1 version

### ISSUE THREAD

**Issue by kretcheu** [mojoTX/xttitle#1]
Hi Mojotx,

I'm a Debian package maintainer of xttitle on Debian distribution.
I want to upgrade the version of Xttitle, so it's nice if you release the 1.1 version.

 Thanks.
 kretcheu

**Comment by mojotx** [comment]
> I'm a Debian package maintainer of xttitle on Debian distribution.
> I want to upgrade the version of Xttitle, so it's nice if you release the 1.1 version.

Hello, @kretcheu ! By 1.1 version, do you mean your pull request adding LDFLAGS to the makefile?

**Comment by mojotx** [comment]
I just bumped the version to v1.2.0, and included your change, along with a little code cleanup.
